/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { gql } from './graphql';
import { choreoClient } from './httpClients';
import type { ComponentDeployment, BuildRun, ReleaseMgtDeployment, DeploymentTrackImage, DeployDeploymentTrackInput, PromoteInput, StopDeploymentInput, DeployPrebuiltImageInput, ByoiImage } from '../../types/deployment';
import type { EnvEndpoint } from '../../types/component';
import type { DeployComponentInput } from '../../types/build';

/** Escapes a string for embedding in a GraphQL inline query string. */
function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const COMPONENT_DEPLOYMENT_QUERY = `
  query GetComponentDeployment($orgHandler: String!, $orgUuid: String!, $componentId: String!, $versionId: String!, $environmentId: String!) {
    componentDeployment(orgHandler: $orgHandler, orgUuid: $orgUuid, componentId: $componentId, versionId: $versionId, environmentId: $environmentId) {
      releaseId, cron, cronTimezone, deploymentStatusV2, invokeUrl, imageUrl, configCount,
      releaseMgtDeployment { releaseMgtReleaseId, releaseMgtDeploymentId, releaseMgtReleaseName },
      build { buildId, deployedAt, runId, commit { sha, message, isLatest, author { name, date, email, avatarUrl } } }
    }
  }`;

const ENV_ENDPOINTS_QUERY = `
  query GetEnvEndpoints($componentId: String!, $versionId: String!, $releaseId: String!) {
    componentEndpoints(input: {
      componentId: $componentId,
      versionId: $versionId,
      options: { filter: { releaseIds: [$releaseId] } }
    }) {
      id, name, createdAt, updatedAt, releaseId, environmentId, displayName, port, type,
      apiContext, apiDefinitionPath, invokeUrl, visibility, networkVisibilities, hostName,
      isAutoGenerated, apimId, apimRevisionId, internalGwRevisionId, externalGwRevisionId,
      apimName, projectUrl, organizationUrl, publicUrl, state,
      stateReason { code message details workerId },
      isDeleted, deletedAt, hasShortUrl, shortUrlReassignState, defaultPublicUrl,
      defaultOrganizationUrl, signature, isScopeAdded, generationSource
    }
  }`;

const DEPLOYMENT_STATUS_QUERY = `
  query GetDeploymentStatus($versionId: String!, $componentId: String!) {
    deploymentStatusByVersion(versionId: $versionId, componentId: $componentId) {
      id, sha, started_at, completed_at, status, conclusion, conclusionV2, isAutoDeploy, isTriggeredAtCreation, name, failureReason, sourceCommitId, buildRef
    }
  }`;

const DEPLOYMENT_TRACK_IMAGES_QUERY = `
  query GetDeploymentTrackImages($componentId: String!, $versionId: String!) {
    deploymentTrackImages(input: { componentId: $componentId, id: $versionId }) {
      imageId, createdAt, updatedAt, commitHash, commitMessage, builtAt, runId,
      author { name, email, date, avatarUrl }
    }
  }`;

const DEPLOY_DEPLOYMENT_TRACK = `
  mutation deployDeploymentTrack($input: DeployDeploymentTrackInput!) {
    deployDeploymentTrack(input: $input)
  }`;

const DEPLOY_COMPONENT = `
  mutation DeployComponent(
    $componentId: String!
    $versionId: String!
    $envId: String!
    $sha: String!
    $branch: String
    $shaDate: String
    $gitRefType: String
    $cron: String
    $cronTimezone: String
    $commitTag: String
  ) {
    deployComponent(deployment: {
      componentId: $componentId,
      versionId: $versionId,
      envId: $envId,
      sha: $sha,
      branch: $branch,
      shaDate: $shaDate,
      gitRefType: $gitRefType,
      cron: $cron,
      cronTimezone: $cronTimezone,
      commitTag: $commitTag
    }) {
      message
      success
    }
  }`;

const PROMOTE_MUTATION = `
  mutation promote($componentId: String!, $promoteSchema: Promote!) {
    promote(componentId: $componentId, promoteSchema: $promoteSchema)
  }`;

const STOP_DEPLOYMENT = `
  mutation StopDeployment($orgHandler: String!, $componentId: String!, $releaseId: String!, $type: String!, $clearCron: Boolean!) {
    stopDeployment(orgHandler: $orgHandler, componentId: $componentId, releaseId: $releaseId, type: $type, clearCron: $clearCron)
  }`;

const REDEPLOY_DEPLOYMENT = `
  mutation RedeployDeployment($orgHandler: String!, $componentId: String!, $releaseId: String!, $type: String!, $releaseMgtReleaseId: String, $releaseMgtDeploymentId: String) {
    redeployDeployment(orgHandler: $orgHandler, componentId: $componentId, releaseId: $releaseId, type: $type, applyConfigUpdates: false, releaseMgtReleaseId: $releaseMgtReleaseId, releaseMgtDeploymentId: $releaseMgtDeploymentId)
  }`;

const DEPLOY_PREBUILT_INTEGRATION = `
  mutation deployPrebuiltIntegration($input: DeployPrebuiltImageInput!) {
    deployPrebuiltIntegration(input: $input)
  }`;

export async function fetchComponentDeployment(orgHandler: string, orgUuid: string, componentId: string, versionId: string, environmentId: string): Promise<ComponentDeployment | null> {
  return gql<{ componentDeployment: ComponentDeployment }>(COMPONENT_DEPLOYMENT_QUERY, { orgHandler, orgUuid, componentId, versionId, environmentId })
    .then((d) => d.componentDeployment)
    .catch((): null => null);
}

export async function fetchEnvEndpoints(componentId: string, versionId: string, releaseId: string): Promise<EnvEndpoint[]> {
  return gql<{ componentEndpoints: EnvEndpoint[] }>(ENV_ENDPOINTS_QUERY, { componentId, versionId, releaseId })
    .then((d) => d.componentEndpoints ?? [])
    .catch(() => []);
}

// ── Raw wire shapes — private to this file. The GraphQL responses come back
// with snake_case fields; mappers below convert them to the camelCase domain
// types declared in `src/types/deployment.ts` before the data leaves this file.

interface RawBuildRun {
  id: number;
  sha: string;
  started_at: string;
  completed_at: string;
  status: string;
  conclusion: string;
  conclusionV2: string;
  isAutoDeploy: boolean;
  isTriggeredAtCreation: boolean;
  name: string;
  failureReason: number;
  sourceCommitId: string;
  buildRef?: string;
}

interface RawReleaseMgtDeployment {
  id: string;
  release_mgt_id: string;
  environment_id: string;
  deployment_name: string;
  attempt: number;
  config_revision: number;
  status: string;
  comment: string;
  deployed_at: string;
  deployed_by: string;
  release_name: string;
  commit_hash: string;
  component_configs: {
    config_mapping_revision: number;
    schema_based_config_revision: number;
    api_settings: string;
  };
  created_at: string;
}

function toBuildRun(raw: RawBuildRun): BuildRun {
  return {
    id: raw.id,
    sha: raw.sha,
    startedAt: raw.started_at,
    completedAt: raw.completed_at,
    status: raw.status,
    conclusion: raw.conclusion,
    conclusionV2: raw.conclusionV2,
    isAutoDeploy: raw.isAutoDeploy,
    isTriggeredAtCreation: raw.isTriggeredAtCreation,
    name: raw.name,
    failureReason: raw.failureReason,
    sourceCommitId: raw.sourceCommitId,
    buildRef: raw.buildRef,
  };
}

function toReleaseMgtDeployment(raw: RawReleaseMgtDeployment): ReleaseMgtDeployment {
  return {
    id: raw.id,
    releaseMgtId: raw.release_mgt_id,
    environmentId: raw.environment_id,
    deploymentName: raw.deployment_name,
    attempt: raw.attempt,
    configRevision: raw.config_revision,
    status: raw.status,
    comment: raw.comment,
    deployedAt: raw.deployed_at,
    deployedBy: raw.deployed_by,
    releaseName: raw.release_name,
    commitHash: raw.commit_hash,
    componentConfigs: {
      configMappingRevision: raw.component_configs.config_mapping_revision,
      schemaBasedConfigRevision: raw.component_configs.schema_based_config_revision,
      apiSettings: raw.component_configs.api_settings,
    },
    createdAt: raw.created_at,
  };
}

export async function fetchDeploymentStatus(componentId: string, versionId: string): Promise<BuildRun[]> {
  return gql<{ deploymentStatusByVersion: RawBuildRun[] }>(DEPLOYMENT_STATUS_QUERY, { versionId, componentId }).then((d) => (d.deploymentStatusByVersion ?? []).map(toBuildRun));
}

export async function fetchReleaseMgtDeployments(orgUuid: string, projectId: string, componentId: string, versionId: string, environmentId: string): Promise<ReleaseMgtDeployment[]> {
  const query = `query {
    componentReleaseMgtDeployments(input: {
      organization_id: "${esc(orgUuid)}"
      project_id: "${esc(projectId)}"
      component_id: "${esc(componentId)}"
      deployment_track_id: "${esc(versionId)}"
      environment_id: "${esc(environmentId)}"
      offset: 0
      limit: 10
    }) {
      deployments {
        id, release_mgt_id, environment_id, deployment_name, attempt,
        config_revision, status, comment, deployed_at, deployed_by,
        release_name, commit_hash,
        component_configs { config_mapping_revision, schema_based_config_revision, api_settings }
        created_at
      }
    }
  }`;
  return gql<{ componentReleaseMgtDeployments: { deployments: RawReleaseMgtDeployment[] } }>(query)
    .then((d) => (d.componentReleaseMgtDeployments?.deployments ?? []).map(toReleaseMgtDeployment))
    .catch(() => [] as ReleaseMgtDeployment[]);
}

export async function fetchDeploymentTrackImages(componentId: string, versionId: string): Promise<DeploymentTrackImage[]> {
  return gql<{ deploymentTrackImages: DeploymentTrackImage[] }>(DEPLOYMENT_TRACK_IMAGES_QUERY, { componentId, versionId })
    .then((d) => d.deploymentTrackImages ?? [])
    .catch(() => [] as DeploymentTrackImage[]);
}

export async function deployDeploymentTrack(input: DeployDeploymentTrackInput): Promise<string> {
  return gql<{ deployDeploymentTrack: string }>(DEPLOY_DEPLOYMENT_TRACK, { input }).then((d) => d.deployDeploymentTrack);
}

export async function triggerBuild(input: DeployComponentInput): Promise<{ message: string; success: boolean }> {
  return gql<{ deployComponent: { message: string; success: boolean } }>(DEPLOY_COMPONENT, {
    componentId: input.componentId,
    versionId: input.versionId,
    envId: input.envId,
    sha: input.sha,
    branch: input.branch,
    shaDate: input.shaDate ?? '',
    gitRefType: input.gitRefType,
    cron: input.cron ?? null,
    cronTimezone: input.cronTimezone ?? '',
    commitTag: input.commitTag ?? null,
  }).then((d) => d.deployComponent);
}

export async function promote(input: PromoteInput): Promise<string> {
  return gql<{ promote: string }>(PROMOTE_MUTATION, {
    componentId: input.componentId,
    promoteSchema: {
      apiVersionId: input.apiVersionId,
      sourceReleaseId: input.sourceReleaseId,
      targetEnvironmentId: input.targetEnvironmentId,
      deploymentPipelineId: input.deploymentPipelineId,
      jobRetryCount: 0,
    },
  }).then((d) => d.promote);
}

export async function stopDeployment(input: StopDeploymentInput): Promise<string> {
  return gql<{ stopDeployment: string }>(STOP_DEPLOYMENT, {
    orgHandler: input.orgHandler,
    componentId: input.componentId,
    releaseId: input.releaseId,
    type: input.type ?? 'scheduledTask',
    clearCron: input.clearCron ?? true,
  }).then((d) => d.stopDeployment);
}

export async function redeployDeployment(input: { orgHandler: string; componentId: string; releaseId: string; type: string; releaseMgtReleaseId?: string; releaseMgtDeploymentId?: string }): Promise<string> {
  return gql<{ redeployDeployment: string }>(REDEPLOY_DEPLOYMENT, input).then((d) => d.redeployDeployment);
}

export async function deployPrebuiltImage(input: DeployPrebuiltImageInput): Promise<string> {
  return gql<{ deployPrebuiltIntegration: string }>(DEPLOY_PREBUILT_INTEGRATION, { input }).then((d) => d.deployPrebuiltIntegration);
}

/** Raw devops REST shape for a BYOI image record. */
interface ByoiImageResponse {
  ID: string;
  image_name: string;
  image_name_with_tag: string;
  trigger_source: 'MANUAL' | 'EXTERNAL';
  UpdatedAt: string;
}

/**
 * BYOI image history from the devops REST API (newest first). Used by the
 * Deploy-page Set Up card for image-based (BYOI/RAG ingestion) components.
 */
export async function fetchByoiImageHistory(orgUuid: string, projectId: string, componentId: string, versionId: string): Promise<ByoiImage[]> {
  const qs = new URLSearchParams({ organization_id: orgUuid, project_id: projectId }).toString();
  // Let network/auth/server errors propagate to the consuming query so it can
  // surface an error state; only an absent `data` field falls back to empty.
  const res = await choreoClient.get<{ data: ByoiImageResponse[] }>(`/devops/1.0.0/api/v1/byoi/components/${encodeURIComponent(componentId)}/versions/${encodeURIComponent(versionId)}/images?${qs}`);
  return (res.data ?? []).map((i) => ({ id: i.ID, imageName: i.image_name, imageUrl: i.image_name_with_tag, triggerSource: i.trigger_source, updatedAt: i.UpdatedAt }));
}
