packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  esbuild: true
  tree-sitter: true
  tree-sitter-json: true

patchedDependencies:
  lucide-react@0.545.0: patches/lucide-react@0.545.0.patch
